on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Format files with Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .

      - name: Run Format Check
        run: npm run format:check

      - name: Run Lint Check
        run: npm run lint:check

      - name: Run Unit Tests
        run: npm run test
